name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      # ----- SERVER -----
      - name: Install server deps (ci)
        working-directory: ./server
        run: npm ci

      - name: Server typecheck
        working-directory: ./server
        run: npx tsc -p ./tsconfig.json --noEmit

      - name: Server lint (optional)
        if: hashFiles('server/package.json') != ''
        working-directory: ./server
        run: npm run lint --if-present

      # ----- CLIENT -----
      - name: Install client deps (ci)
        working-directory: ./client
        run: npm ci

      - name: Build client (if present)
        if: hashFiles('client/package.json') != ''
        working-directory: ./client
        run: npm run build --if-present
