name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install (root, workspaces)
        run: npm ci

      # ---- Server ----
      - name: Lint server
        run: npm run -w server lint --if-present
      - name: Typecheck server
        run: npm run -w server typecheck --if-present
      - name: Build server
        run: npm run -w server build --if-present
      - name: Test server
        run: npm test -w server --if-present

      # ---- Client ----
      - name: Lint client
        run: npm run -w client lint --if-present
      - name: Typecheck client
        run: npm run -w client typecheck --if-present
      - name: Build client
        run: npm run -w client build --if-present
      - name: Test client
        run: npm test -w client --if-present
